learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs'))
]

learning_logs/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^topics/$', views.topics, name='topics'),
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    re_path(r'^delete_entry(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry')
]

users/urls.py
from django.urls import re_path
from django.contrib.auth.views import LoginView, LogoutView

from . import views


urlpatterns = [
    re_path(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^register/$', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = '主题'
        verbose_name_plural = '主题'

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '条目'
        verbose_name_plural = '条目'

    def __str__(self):
        if len(str(self.text)) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = {'text'}
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm

    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    else:
        entry.delete()
        return HttpResponseRedirect(reverse('learning_logs:topic'), args=[topic.id])

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @font-face {
            font-family: 'alibaba';
            font-display: swap;
            src: url('//at.alicdn.com/t/webfont_etpup3kg5me.eot'); /* IE9*/
            src: url('//at.alicdn.com/t/webfont_etpup3kg5me.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('//at.alicdn.com/t/webfont_etpup3kg5me.woff2') format('woff2'),
            url('//at.alicdn.com/t/webfont_etpup3kg5me.woff') format('woff'), /* chrome、firefox */ url('//at.alicdn.com/t/webfont_etpup3kg5me.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/ url('//at.alicdn.com/t/webfont_etpup3kg5me.svg#Alibaba-PuHuiTi-Regular') format('svg'); /* iOS 4.1- */
        }
        * {
            font-family: "alibaba", "Microsoft YaHei UI",sans-serif;
        }
    </style>
    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!--Static navbar-->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习笔记</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>你好，{{ user.username }}</a></li>
                    <li><a href="{% url 'users:logout' %}">登出</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse-->
    </div>
</nav>
<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div><!-- /container-->
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
<h3>编辑条目</h3>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn button-primary">保存更改</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>追踪你的进度</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册一个账户</a>去制作你个人的学习笔记，并且列出你正在学习的主题。
    </h2>
    <h2>
        无论何时你正在学习主题的新内容，创建一个条目去总结你学习到了什么
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h2>
{% endblock header %}
{% block content %}
    <p>添加新的条目</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn button-primary">新建条目</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>添加一个新的主题</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">新建主题</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>{{ topic }}的条目</h2>
{% endblock header %}
{% block content %}
    <input value="新建条目" type="button" onclick="location.href='{% url 'learning_logs:new_entry' topic.id %}'"
           class="btn button-primary">
    <br><br>
    {% bootstrap_alert "no" alert_type="warning" %}

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <input value="编辑条目"
                               type="button"
                               onclick="location.href='{% url 'learning_logs:edit_entry' entry.id %}'"
                               class="btn button-default btn-sm">
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div><!--panel-->
    {% empty %}
        还没有这个主题的条目
    {% endfor %}
    <input value="返回主题列表" type="button" onclick="location.href='{% url 'learning_logs:topics' %}'"
           class="btn button-primary">


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
    <h1>主题</h1>
{% endblock header %}
{% block content %}

    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>还没有添加主题，你可以<a href="{% url 'learning_logs:new_topic' %}">新建主题</a></li>
        {% endfor %}
    </ul>
    <input value="新建主题" type="button" onclick="location.href='{% url 'learning_logs:new_topic' %}'" class="btn button-primary btn-lg">

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>登录到你的账户</h2>
{% endblock header %}


{% block content %}
    {% if form.errors %}
        {% bootstrap_alert "你的用户名或密码不正确，请重试" alert_type="warning" %}
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-primary">登录</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>注册用户</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn button-primany">注册</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
    </form>
{% endblock content %}